### PR TITLE
Update to pg 2.17

### PR DESCRIPTION
**Pull request by drgrice1**
Update the standalone renderer to use pg version 2.17.

The entire lib/WeBWorK/htdocs directory has been removed.  The few files that are needed by the standalone renderer are now in public/Problem and public/PGCodeMirror.

To make this work, static file handling had to be revises.  See lib/RenderApp/Controller/StaticFiles.pm.  Basically, the only files that are served from `webwork2_files` are CAPA_graphics files (now served directly from `Contrib/CAPA/CAPA_graphics`) or tmp files (served from a directory in the app root name `tmp`).  PG files are served from the `pg_files` location (files are in `lib/PG/htdocs`).

A `getAssetURL` method is in `lib/WeBWorK/lib/WeBWorK/Utils.pm` much like webwork2's method handles the correct redirection of the `pg_files`.

Note that codemirror is no longer serving their javascript and css files.  So temporarily this has add an `npm install` step in the root directory of the renderer.  A `vendor` link in public makes those files available.  We can either switch to another CDN to serve those files or go with this.  I much prefer this.  CDN's are not reliable.  I think it would be best to switch all third party javascript to using this approach.

Note that MathQuill is now optional much the same way as in #83, but the default is that it is enabled.  Of course, the standalone renderer no longer adds MathQuill itself as PG now does that.

I recommend running `git diff develop :^lib/WeBWorK/htdocs` from this branch to see the changes without the lengthy list of deletions from the lib/WeBWorK/htdocs directory.

### CODE REVIEW

**Comment by drgrice1** [comment]
This repository really needs to become the primary repository for the standalone renderer, and not @drdrew42's repository.  The same needs to be true of the OPLv3 repository if these are going to be considered for use with webwork.

**Review by drdrew42 — APPROVED** [review]
Tested and everything works great!
Caveats: 
- make sure Mojolicious is updated (and Future::AsyncAwait as well), needs 9.17+
- git submodule update (for PG)
- npm install x2 (for app AND for PG)

**Comment by taniwallach** [comment]
> This repository really needs to become the primary repository for the standalone renderer, and not @drdrew42's repository. The same needs to be true of the OPLv3 repository if these are going to be considered for use with webwork.

Could the ownership of the root level repository be transferred to openwebwork?

**Review by taniwallach — APPROVED** [review]
I tested this at and posted comments about the Docker build issues I ran into at https://github.com/drdrew42/renderer/pull/89#issuecomment-1191448709 and some general comment at https://github.com/drdrew42/renderer/pull/89#issuecomment-1191504926.

This works and even supports right-to-left (Hebrew) problems better than was the case in the old version where a special `rtl.css` was added (via a local hack).

**Comment by drgrice1** [comment]
@taniwallach:  What do you mean by root level ownership?  Do you mean the github reference that this is forked from drdrew42/renderer?

**Comment by taniwallach** [comment]
> @taniwallach: What do you mean by root level ownership? Do you mean the github reference that this is forked from drdrew42/renderer?

Yes, and more. The tree shown at https://github.com/openwebwork/renderer/network/members would also then show openwebwork as the "root" of the tree of forks.

I am more interested is trying to have the PR history, discussions, etc. move over to this repository if that is possible. AFAIK a transfer of repository ownership in GitHub would keep all that as part of what would be available.

**Comment by drgrice1** [comment]
@pstaabp:  There is no need to change the quasar.conf.js for webwork3.  Check your render_app.conf file.

**Comment by drdrew42** [comment]
@pstaabp asset URLs should now be fixed -- I had a similar issue with requests being misrouted. No need to change anything else, just pull the latest updates to this branch.

**Comment by drdrew42** [comment]
Also, be sure to run `npm install` in both the renderer root and `lib/PG`

**Comment by pstaabp** [comment]
With the newest changes, everything is working out of the box, except the following warning:
```
Use of uninitialized value in substitution iterator at /opt/webwork/renderer/lib/RenderApp/Controller/FormatRenderedProblem.pm line 307.
```

**Comment by drgrice1** [comment]
@pstaabp:  The use of uninitialized value warnings are caused by the variables $LTIGradeMessage and $problemSeed being in the ww3_format.pl file, but never defined in the preceding code of FormatRenderedProblem.pm.  The same things happens for the other formats when using the standalone renderer directly.  Unfortunately the substitution `s/(\$\w+)/"defined $1 ? $1 : ''"/gee` does not work to avoid those warnings.  I think it may have been believed that by using the `defined $1 ? $1 : ''` part it would avoid that but it doesn't.  In any case, this is not caused by this pull request.

**Pull request merged**
